
db:
  image: mongo:3.2.0

web:
  extends:
    file: docker-compose-common.yml
    service: web
  volumes:
  - ./src:/src
  entrypoint: ./node_modules/node-dev/bin/node-dev
  command: --poll --no-deps index.js
  links:
  - db
  ports:
  - '80:3000'
