version: '3'
services:
  db:
    image: mongo:3.4.1
    ports:
      - '27017:27017'
  main:
    image: node:6.9.5
    ports:
      - '80:80'
      - '3000:3000'
      - '3001:3001'
    working_dir: /app/src
    volumes:
      - .:/app
