box:
  id: node
  tag: 6.9.5
  ports:
    - '80'
    - '3000'
    - '3001'

services:
  - id: mongo
    tag: 3.4.1
    ports:
     - '27017'

dev:
  steps:
    - script:
        name: check local environment
        code: |
          [[ -f ENVIRONMENT_LOCAL || "$(cat ENVIRONMENT_LOCAL.template | xargs)" == "" ]] || ( echo "No ENVIRONMENT_LOCAL present, please create one based on ENVIRONMENT_LOCAL.template" && exit 1 )
        cwd: $WERCKER_ROOT
    - npm-install:
        name: install node dependencies
        options: --no-optional
    - script:
        name: adding tools
        code: |
          ln -s "$WERCKER_ROOT/tools/log" /usr/bin/log
          ln -s "$WERCKER_ROOT/tools/reload" /usr/bin/reload
          ln -s "$WERCKER_ROOT/tools/reload" /usr/bin/restart
    - script:
        name: run
        code: |
          touch /var/log/keystone.log
          touch /var/log/webpack.log
          npm run dev >> /var/log/webpack.log 2>&1 &
          npm run watch >> /var/log/keystone.log 2>&1 &
    - internal/shell:
        code: |
          stty columns $TERMINAL_COLUMNS
          stty rows $TERMINAL_ROWS
          log

build:
  steps:
    - npm-install:
        name: install node dependencies
        options: --no-optional --silent
        cwd: $WERCKER_ROOT/src
    - npm-test:
        name: run tests
        cwd: $WERCKER_ROOT/src
    - script:
        name: run webpack
        code: npm run webpack -- -p
        cwd: $WERCKER_ROOT/src
    - script:
        name: export the application
        code: |
          cp -r src "$WERCKER_OUTPUT_DIR"
          cp -r dokku "$WERCKER_OUTPUT_DIR"
          mv "$WERCKER_OUTPUT_DIR/dokku/Dockerfile" "$WERCKER_OUTPUT_DIR/Dockerfile"

deploy-dokku:
  steps:
    - add-to-known_hosts:
        hostname: $DOKKU_HOST
    - add-ssh-key:
        keyname: DOKKU_KEY
    - script:
        name: Initialize new repository
        code: |
          rm -rf .git
          git init
          git config --global user.name "wercker"
          git config --global user.email "pleasemailus@wercker.com"
          git remote add dokku dokku@$DOKKU_HOST:$DOKKU_APP
    - script:
        name: Add everything to the repository
        code: |
          git add .
          git commit --quiet -m "Result of deploy $WERCKER_GIT_COMMIT"
    - script:
        name: Push to dokku
        code: |
          git push -f dokku master

deploy-swarm:
  steps:
    - internal/docker-push:
        username: $DOCKER_REGISTRY_USERNAME
        password: $DOCKER_REGISTRY_PASSWORD
        tag: $WERCKER_GIT_COMMIT
        repository: $DOCKER_REGISTRY_REPO
        registry: $DOCKER_REGISTRY
        working-dir: $WERCKER_ROOT/src
        cmd: node index
        env:
          - NODE_ENV=production
          - DEBUG=app,app,app:*
          - DEBUG_COLORS=1
        ports: "80"
    - add-to-known_hosts:
        name: add to known hosts
        hostname: $DOCKER_SWARM_MANAGER
    - add-ssh-key:
        name: add ssh key
        keyname: DOCKER_SWARM_KEY
    - weyforth/docker-swarm@0.1.1:
        name: deploy image
        manager: $DOCKER_SWARM_MANAGER
        user: $DOCKER_SWARM_USER
        service: $DOCKER_SWARM_SERVICE
        image: $DOCKER_REGISTRY_REPO
        tag: $WERCKER_GIT_COMMIT
