box:
  id: node
  tag: 5.10.0

services:
  - id: mongo
    tag: 3.2.4

dev:
  steps:
    - npm-install
    - internal/shell:
        code: |
          npm run dev &
          npm run watch &

build:
  steps:
    - npm-install
    - npm-test
    - script:
        name: run webpack
        code: npm run webpack -- -p
    - script:
        name: generate kubernetes controller file
        code: cat node.yaml | while read line; do echo $(eval echo "\"${line//\"/\\\"}\""); done > node-controller.yaml
  after-steps:
    - install-packages:
        packages: ruby
    # - wantedly/pretty-slack-notify:
    #     webhook_url: $SLACK_WEBHOOK_URL
    #     username: $SLACK_USERNAME

deploy:
  steps:
    - script:
        name: install gcloud
        code: |
          curl https://sdk.cloud.google.com | bash
          source ~/.bashrc
    - script:
        name: install jq
        code: |
          wget -O /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.5rc1/jq-linux-x86_64-static
          chmod a+x /usr/local/bin/jq
    - script:
        name: gcr.io authentication
        code: |
          gcloud auth activate-refresh-token $GCLOUD_ACCOUNT $GCLOUD_REFRESH_TOKEN
          gcloud docker --authorize-only
          export GCR_AUTH_TOKEN=$(cat $HOME/.dockercfg | jq --raw-output '.["https://gcr.io"].auth' | base64 --decode | cut -d ':' -f2)
    - internal/docker-push:
        username: _token
        password: $GCR_AUTH_TOKEN
        repository: gcr.io/$GCR_PROJECT/$GCR_IMAGE
        tag: $WERCKER_GIT_COMMIT
        registry: https://gcr.io

  initialize:
    - kubectl:
        server: $GCE_SERVER
        username: $GCE_USERNAME
        password: $GCE_PASSWORD
        insecure-skip-tls-verify: true
        command: create -f node-controller.yml

    - kubectl:
        server: $GCE_SERVER
        username: $GCE_USERNAME
        password: $GCE_PASSWORD
        insecure-skip-tls-verify: true
        command: create -f node-service.json

  rolling-update:
    - kubectl:
        server: $GCE_SERVER
        username: $GCE_USERNAME
        password: $GCE_PASSWORD
        insecure-skip-tls-verify: true
        command: rolling-update node
        image: gcr.io/$GCR_PROJECT/$GCR_IMAGE:$WERCKER_GIT_COMMIT

    # - add-to-known_hosts:
    #     hostname: $DOKKU_HOSTNAME
    # - add-ssh-key:
    #     keyname: DOKKU_KEY
    # - script:
    #     name: copy environment to file
    #     code: env > ENVIRONMENT
    # - script:
    #     name: Initialize new repository
    #     code: |
    #       rm -rf .git
    #       git init
    #       git config --global user.name "wercker"
    #       git config --global user.email "pleasemailus@wercker.com"
    #       git remote add dokku dokku@$DOKKU_HOSTNAME:keystone-framework
    # - script:
    #     name: Add everything to the repository
    #     code: |
    #       git add .
    #       git commit -m "Result of deploy $WERCKER_GIT_COMMIT"
    # - script:
    #     name: Push to dokku
    #     code: |
    #       git push dokku master -f
